import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { useNavigate } from "react-router-dom";
import {
  updateFranchise,
  fetchByIdFranchise,
} from "../../api/Franchise-Api/FranchiseApi";

const useEditFranchise = () => {
  const [formData, setFormData] = useState({
    name: "",
    icon: null as File | null,
    photo: "",
    photo2: null as File | null,
    featured: 0,
    prodtype: 0,
    status: 1,
    srno: 1.0,
    createddate: new Date().toISOString(),
    modifieddate: null as string | null,
    roll: 5,
    createdby: 2091,
    modifiedby: 0,
    push_flag: false,
    delete_flag: false,
    modified_time: new Date().toISOString(),
    franchiseName: "",
    shopName: "",
    emailId: "",
    mobileNo: "",
    anotherMobileNo: "",
    shopLocation: "",
    details: "",
    address: "",
    sellBy: "",
    sellAmount: "",
    sellDate: "",
    franchiseType: "",
    latitude: "",
    longitude: "",
    FrontAdharcardPhoto: "",
    BackAdharcardPhoto: "",
    AdharNo: 0,
    PanNo: 0,
    FrontPanPhoto: "",
    BackPanPhoto: "",
    GSTINNo: 0,
    gstCretificate: "",
    GumastaNo: 0,
    GumastaCretificate: "",
    MSMENo: 0,
    MSMECertificate: "",
    UploadFoodLicense: "",
    UploadFoodLicenseReceipt: "",
    UploadAgreementCopy: "",
    BankHolderName: "",
    BankName: "",
    AccountNo: 0,
    Branch: "",
    IFSCCode: "",
    UPIID: "",
    BankAccountStatus: "",
    StateId: 1 as number,
  });
  const [message, setMessage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const { id } = useParams();
  const navigate = useNavigate();

  useEffect(() => {
    fetchFranchiseById();
  }, []);

  const handleChange = (e: any) => {
    const { name, value, files } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: files && files.length > 0 ? files[0] : value,
    }));
    if (files) {
      const url = URL.createObjectURL(files[0]);
      setFormData((prev) => ({
        ...prev,
        photo: url,
      }));
    }
  };
  const fetchFranchiseById = async () => {
    try {
      const response: any = await fetchByIdFranchise(Number(id));
      if (response.status === 200 && response.data) {
        const franchiseData = response.data;
        setFormData((prev) => ({
          ...prev,
          name: franchiseData.Fname || "",
          icon: null,
          photo: franchiseData.Photo || "",
          photo2: null,
          featured: 0,
          prodtype: 0,
          status: parseInt(franchiseData.Status) || 1,
          srno: 1.0,
          createddate: franchiseData.CreatedDate || new Date().toISOString(),
          modifieddate: franchiseData.ModifiedDate || null,
          roll: parseInt(franchiseData.Roll) || 5,
          createdby: parseInt(franchiseData.CreatedBy) || 2091,
          modifiedby: parseInt(franchiseData.ModifiedBy) || 0,
          push_flag: franchiseData.push_flag === "true",
          delete_flag: franchiseData.delete_flag === "true",
          modified_time:
            franchiseData.modified_time || new Date().toISOString(),
          franchiseName: franchiseData.Fname || "",
          shopName: franchiseData.ShopName || "",
          emailId: franchiseData.EmailId || "",
          mobileNo: franchiseData.Phone || "",
          anotherMobileNo: franchiseData.Phone2 || "",
          shopLocation: franchiseData.Location || "",
          details: franchiseData.Details || "",
          address: franchiseData.Address || "",
          sellBy: franchiseData.SellAmt ? "Amount" : "",
          sellAmount: franchiseData.SellAmt || "",
          sellDate: franchiseData.SellDate || "",
          franchiseType: franchiseData.TypeOfVendor || "",
          latitude: franchiseData.Lattitude || "",
          longitude: franchiseData.Longitude || "",
          FrontAdharcardPhoto: franchiseData.AadharCard || "",
          BackAdharcardPhoto: franchiseData.AadharCard2 || "",
          AdharNo: parseInt(franchiseData.AadharNo) || 0,
          PanNo: parseInt(franchiseData.PanNo) || 0,
          FrontPanPhoto: franchiseData.PanCard || "",
          BackPanPhoto: franchiseData.PanCard2 || "",
          GSTINNo: franchiseData.GstNo || 0,
          gstCretificate: franchiseData.GstCertificate || "",
          GumastaNo: parseInt(franchiseData.GumastaNo) || 0,
          GumastaCretificate: franchiseData.Gumasta || "",
          MSMENo: parseInt(franchiseData.MsmeNo) || 0,
          MSMECertificate: franchiseData.Msme || "",
          UploadFoodLicense: franchiseData.FoodLicence || "",
          UploadFoodLicenseReceipt: franchiseData.FoodLicenceReceipt || "",
          UploadAgreementCopy: franchiseData.AgreementCopy || "",
          BankHolderName: franchiseData.AccountName || "",
          BankName: franchiseData.BankName || "",
          AccountNo: parseInt(franchiseData.AccountNo) || 0,
          Branch: franchiseData.Branch || "",
          IFSCCode: franchiseData.IfscCode || "",
          UPIID: franchiseData.UpiNo || "",
          BankAccountStatus: franchiseData.Status,
        }));
      }
    } catch (error) {
      console.error("Error fetching franchise data:", error);
    }
  };

  const formatDate = (dateString: string) => {
    if (!dateString) return "";
    const date = new Date(dateString);
    const day = String(date.getDate()).padStart(2, "0");
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const year = date.getFullYear();
    return `${year}-${month}-${day}`;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setMessage(null);
    setIsLoading(true);

    const payload = {
      BeneficiaryId: "",
      Taluka: "",
      Village: "",
      District: "",
      PumpCapacity: "",
      RooftopPlantCapacity: "",
      OffOnGrid: "",
      SanctionLoad: "",
      LoadExtension: "",
      WaterSource: "",
      SummerDepth: "",
      WinterDepth: "",
      PumpHead: "",
      BgNumber: "",
      BgValidity: "",
      BgClaimPeriod: "",
      InsuranceNumber: "",
      InsuranceAgency: "",
      InsuranceValidity: "",
      InstallationVendor: "",
      PumpHeadSelect: 0,
      AcDc: "",
      Surface: "",
      RefPhone: null,
      RefPhone2: null,
      RefEmailId: null,
      ShopName: formData.shopName,
      Fname: formData.franchiseName,
      Lattitude: formData.latitude,
      Longitude: formData.longitude,
      Details: formData.details || null,
      Location: formData.shopLocation,
      Phone: formData.mobileNo,
      Phone2: formData.anotherMobileNo,
      EmailId: formData.emailId,
      SellAmt: formData.sellAmount,
      SellDate: formatDate(formData.sellDate),
      TypeOfVendor: formData.franchiseType,
      AadharNo: formData.AdharNo,
      AadharCard: formData.FrontAdharcardPhoto,
      AadharCard2: formData.BackAdharcardPhoto,
      Address: formData.address,
      PanNo: formData.PanNo,
      PanCard: formData.FrontPanPhoto,
      PanCard2: formData.BackPanPhoto,
      GstNo: formData.GSTINNo,
      GstCertificate: formData.gstCretificate,
      GumastaNo: formData.GumastaNo,
      Gumasta: formData.GumastaCretificate,
      MsmeNo: formData.MSMENo,
      Msme: formData.MSMECertificate,
      FoodLicence: formData.UploadFoodLicense,
      FoodLicenceReceipt: formData.UploadFoodLicenseReceipt,
      AgreementCopy: formData.UploadAgreementCopy,
      BankName: formData.BankName,
      AccountName: formData.BankHolderName,
      AccountNo: formData.AccountNo,
      Branch: formData.Branch,
      IfscCode: formData.IFSCCode,
      UpiNo: formData.UPIID,
      Status: formData.status,
      CustomerId: "F96673253",
      ColgId: 0,
      Mname: "",
      Lname: "",
      Password: "",
      CountryId: 0,
      StateId: formData.StateId,
      CityId: 0,
      AreaId: null,
      Pincode: "",
      Photo: null,
      Photo2: null,
      Photo3: null,
      Roll: formData.roll,
      CreatedBy: 5,
      ModifiedBy: 5,
      CreatedDate: formatDate(new Date().toISOString()),
      ModifiedDate: formatDate(new Date().toISOString()),
      Options:
        "10,11,14,48,49,50,56,57,59,60,69,71,73,74,77,78,79,80,81,82,84,85,86,92,93,94,96,97,98,99",
      BranchId: "",
      Dob: null,
      Area: "",
      UserType: 0,
      PayMode: null,
      UnderUser: 0,
      ProjectType: "",
      InspectionDate: null,
      CommissioningDate: null,
      CustType: 0,
      CatId: "0",
      CompName: "",
      CompAddress: "",
      CompPhone: "",
      AuthorName: "",
      Tokens: localStorage.getItem("authToken"),
      AuthToken: null,
      CompId: 0,
      FatherPhone: null,
      Designation: null,
      BloodGroup: null,
      JoinDate: null,
      EmailId2: null,
      PerDaySalary: null,
      Barcode: "",
      KycStatus: 0,
      KycDate: null,
      Profession: null,
      FsiicNo: null,
      ShopActNo: null,
      AnniversaryDate: null,
      ExeId: 0,
      UnderFr: 0,
      ReportingMgr: 0,
      ResignStatus: 0,
      ResignDate: null,
      ResignComment: null,
      BillSoftFrId: 0,
      PkgId: 0,
      PkgAmt: 1.0,
      PkgDiscount: formatDate(new Date().toISOString()),
      PkgDate: formatDate(new Date().toISOString()),
      PkgValidity: 0,
      Prime: 0,
      terms_condition: "Thank you for your business!",
      bottom_title: "Powered by MAHACHAI PRIVATE LIMITED",
      ReferCode: null,
      OwnFranchise: 1,
      PrintCompName: "MAHACHAI PRIVATE LIMITED",
      PrintMobNo: "",
      TableQrCode: null,
      SalaryType: 0,
      CreditSalaryStatus: 0,
      IdStatus: 0,
      selectedZone: "",
      CocoFranchiseAccess: null,
      CinNo: null,
      push_flag: 0,
      delete_flag: 0,
      modified_time: formatDate(new Date().toISOString()),
      UnderFrId: 0,
      ShowFrStatus: 1,
      ReferalNo1: null,
      ReferalNo2: null,
      NomineePartnerName: null,
      NomineePartnerRelation: null,
      NomineePartnerPhone: null,
      BillAmount: 0,
      ExpCatId: 0,
      MainBrEmp: 0,
      ExpApproval: 0,
      UnderByUser: 0,
      DeliveryPerson: 0,
      ChequeBook: null,
      TradeName: null,
      AllocateProd: 1,
      AllocateRawProd:
        "1328,1327,1326,1325,1324,1323,1322,1321,1320,1319,1318,1317,1193,1192,1127,730,711,710,709,708,707,706,705,704,598,597,596,595,594,593,592,591,590,589,588,587,586,585,584,583,582,581,580,579,578,577,576,575,574,573,572,571,570,569,568,567,566,565,564,563,562,561,560,559,558,557,556,555,554,553,552,551,550,549,548,547,545,544,543,542,541,540,539,538,537,536,535,534,533,532,531,530,529,528,527,526,525,524,523,522,521,520,519,518,517,516,515,514,513,512,511,510,509,508,507,506,505,504,503,502,501,500,499,498,497,496,495,494,493,492,491,490,489,488,487,486,485,484,483,482,481,480,479,478,477,476,475,474,473,472,471,470,469,468,467,466,465,464,463,462,461,460,459,458,457,456,455,454,453,452,451,450,449,448,446,445,444,443,442,441,440,439,438,437,436,435,434,433,432,431,430,429,427,426,425,424,423,422,421,420,419,417,416,415,414,413,412,411,410,408",
      ZoneId: 1,
      BoreDia: "",
      zone: null,
      SchemeId: 0,
      SurveyDetails: 0,
      Percentage: null,
      DeclarationPdf: null,
      NomineeName: null,
      NomineeRelation: null,
      NomineePhone: null,
      NomineeAadharNo: null,
      MonthlySalary: null,
      DeclarationPhoto: null,
      MgrCheckpoint: 0,
      OtherEmp: 0,
    };

    try {
      const response = await updateFranchise(Number(id), Object(payload));
      if (response.status === 200) {
        setMessage("Franchise update successfully!");
        navigate("/Franchise/ViewFranchise");
        setFormData({
          name: "",
          icon: null,
          photo: "",
          photo2: null,
          featured: 0,
          prodtype: 0,
          status: 1,
          srno: 1.0,
          createddate: new Date().toISOString(),
          modifieddate: null,
          roll: 5,
          createdby: 2091,
          modifiedby: 0,
          push_flag: false,
          delete_flag: false,
          modified_time: new Date().toISOString(),
          franchiseName: "",
          shopName: "",
          emailId: "",
          mobileNo: "",
          anotherMobileNo: "",
          shopLocation: "",
          details: "",
          address: "",
          sellBy: "",
          sellAmount: "",
          sellDate: "",
          franchiseType: "",
          latitude: "",
          longitude: "",
          FrontAdharcardPhoto: "",
          BackAdharcardPhoto: "",
          AdharNo: 0,
          PanNo: 0,
          FrontPanPhoto: "",
          BackPanPhoto: "",
          GSTINNo: 0,
          gstCretificate: "",
          GumastaNo: 0,
          GumastaCretificate: "",
          MSMENo: 0,
          MSMECertificate: "",
          UploadFoodLicense: "",
          UploadFoodLicenseReceipt: "",
          UploadAgreementCopy: "",
          BankHolderName: "",
          BankName: "",
          AccountNo: 0,
          Branch: "",
          IFSCCode: "",
          UPIID: "",
          BankAccountStatus: "",
          StateId: 1,
        });
      } else {
        setMessage(`Error: Failed to Edit Franchise.`);
      }
    } catch (err: any) {
      console.error("Error during Edit Franchise :", err);
      setMessage("Network error. Please try again later.");
    } finally {
      setIsLoading(false);
    }
  };

  return {
    formData,
    message,
    isLoading,
    handleChange,
    handleSubmit,
  };
};

export default useEditFranchise;
