name: Deploy React App

on:
  push:
    branches:
      - main
      - dev
      - test
      - stag

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<EC2_IP> << 'EOF'
          cd /path/to/react-multi-branch-deploy
          git fetch origin ${{ github.ref_name }}
          git reset --hard origin/${{ github.ref_name }}
          bun install
          case "${{ github.ref_name }}" in
            main)
              pm2 restart main --update-env
              ;;
            dev)
              pm2 restart dev --update-env
              ;;
            test)
              pm2 restart test --update-env
              ;;
            stag)
              pm2 restart stag --update-env
              ;;
          esac
          EOF
