name: Deploy React App with Docker

on:
  push:
    branches:
      - main
      - dev
      - test
      - stag
      - dockertest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log into Docker Hub using credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image from Dockerfile
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kwick-ui-frontend:$GITHUB_SHA .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/kwick-ui-frontend:$GITHUB_SHA

      # Set up SSH key for EC2 access
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to EC2 and Run Docker container
      - name: Deploy to EC2 and Run Docker container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            # Step 1: Stop and remove the existing container if it exists
            if [ \$(docker ps -aq -f name=kwick-ui-frontend-container) ]; then
              docker stop kwick-ui-frontend-container
              docker rm kwick-ui-frontend-container
            fi

            # Step 2: Check if any process is using port 5177 and kill it if necessary
            sudo lsof -t -i:5177 | xargs -r sudo kill -9

            # Step 3: Clean up unused Docker networks and volumes
            docker network prune -f
            docker volume prune -f

            # Step 4: Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/kwick-ui-frontend:$GITHUB_SHA

            # Step 5: Run the new Docker container on a different external port (5180) if needed
            docker run -d -p 5180:5177 --name kwick-ui-frontend-container ${{ secrets.DOCKER_USERNAME }}/kwick-ui-frontend:$GITHUB_SHA
          "
