name: Deploy React App

on:
  push:
    branches:
      - main
      - dev
      - test
      - stag

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "bash -s" <<EOF
          set -e
          cd /path/to/react-multi-branch-deploy
          git fetch origin $BRANCH_NAME
          git reset --hard origin/$BRANCH_NAME
          bun install
          case "$BRANCH_NAME" in
            main)
              pm2 restart main --update-env
              ;;
            dev)
              pm2 restart dev --update-env
              ;;
            test)
              pm2 restart test --update-env
              ;;
            stag)
              pm2 restart stag --update-env
              ;;
          esac
          EOF
