name: Deploy React App

on:
  push:
    branches:
      - main
      - dev
      - test
      - stag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          # Extract branch name
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch Name: $BRANCH_NAME"

          # Validate branch name
          if [ -z "$BRANCH_NAME" ]; then
            echo "Error: Branch name is empty!"
            exit 1
          fi

          # Ensure the branch exists in the repository
          BRANCH_EXISTS=$(git ls-remote --heads https://github.com/persistsolution/kwick-ui-frontend.git "$BRANCH_NAME")
          if [ -z "$BRANCH_EXISTS" ]; then
            echo "Error: Branch '$BRANCH_NAME' does not exist in the repository!"
            exit 1
          fi

          echo "Deploying branch: $BRANCH_NAME to EC2 instance at ${{ secrets.EC2_HOST }}"
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            set -e
            echo 'Connected to EC2. Starting deployment for branch: $BRANCH_NAME'

            # Define variables
            PROJECT_DIR=\"/home/ubuntu/kwick-ui-frontend/\$BRANCH_NAME\"

            # Ensure Bun is installed
            if ! command -v bun &> /dev/null; then
              echo 'Bun is not installed. Installing Bun...'
              curl -fsSL https://bun.sh/install | bash
              export PATH=\"\$HOME/.bun/bin:\$PATH\"
              source ~/.bashrc
            fi

            echo 'Bun is installed at: $(command -v bun)'

            # Clone repository for the branch
            if [ -d \"\$PROJECT_DIR\" ]; then
              echo 'Directory exists for branch. Cleaning up.'
              sudo rm -rf \"\$PROJECT_DIR\"
            fi
            git clone --branch \"\$BRANCH_NAME\" https://github.com/persistsolution/kwick-ui-frontend.git \"\$PROJECT_DIR\"

            # Navigate to the directory and install dependencies
            cd \"\$PROJECT_DIR\"
            bun install --no-cache

            # Start or restart the application using PM2
            PORT_MAP=(\"main:5173\" \"dev:5174\" \"test:5175\" \"stag:5176\")
            PORT=0
            for MAPPING in \${PORT_MAP[@]}; do
              if [[ \"\$MAPPING\" == \"\$BRANCH_NAME\"* ]]; then
                PORT=\${MAPPING#*:}
                break
              fi
            done

            if pm2 list | grep -q \"\$BRANCH_NAME\"; then
              pm2 restart \"\$BRANCH_NAME\" --update-env
            else
              pm2 start \"bun dev --port \$PORT\" --name \"\$BRANCH_NAME\" --cwd \"\$PROJECT_DIR\"
            fi

            pm2 save
            echo 'Deployment for branch: $BRANCH_NAME completed.'
          "
