name: Deploy React App

on:
  push:
    branches:
      - main
      - dev
      - test
      - stag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Branch Name
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Extracted Branch Name: $BRANCH_NAME"
          if [ -z "$BRANCH_NAME" ]; then
            echo "Error: Branch name is empty!"
            exit 1
          fi

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Simulate Docker Build and Push
        run: |
          echo "Simulating Docker process for branch: $BRANCH_NAME"
          IMAGE_NAME="kwick-ui-frontend:${BRANCH_NAME}"
          echo "Step 1: Building Docker image: $IMAGE_NAME"
          echo "Step 2: Tagging Docker image"
          echo "Step 3: Pushing Docker image to repository: ${{ secrets.DOCKER_REPO }}/$IMAGE_NAME"
          echo "Docker process simulation completed!"

      - name: Simulate EC2 Deployment
        run: |
          echo "Simulating EC2 deployment for branch: $BRANCH_NAME"
          echo "Step 1: Connecting to EC2 instance at ${{ secrets.EC2_HOST }}"
          echo "Step 2: Pulling Docker image: ${{ secrets.DOCKER_REPO }}/kwick-ui-frontend:$BRANCH_NAME"
          echo "Step 3: Stopping and removing existing container for branch: $BRANCH_NAME"
          echo "Step 4: Running new Docker container on port 3000"
          echo "EC2 deployment simulation completed!"
