name: Deploy React App

on:
  push:
    branches:
      - main
      - dev
      - test
      - stag
      - dockertest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Deploying branch: $BRANCH_NAME to EC2 instance at ${{ secrets.EC2_HOST }}"

          # Validate branch exists
          BRANCH_EXISTS=$(git ls-remote --heads https://github.com/persistsolution/kwick-ui-frontend.git "$BRANCH_NAME")
          if [ -z "$BRANCH_EXISTS" ]; then
            echo "Error: Branch '$BRANCH_NAME' does not exist in the repository!"
            exit 1
          fi

          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            set -e
            echo 'Connected to EC2. Deploying branch: $BRANCH_NAME'

            PROJECT_DIR='/home/ubuntu/kwick-ui-frontend/$BRANCH_NAME'
            PORT=5177

            if [ -d \"\$PROJECT_DIR\" ]; then
              echo \"Cleaning up existing directory: \$PROJECT_DIR\"
              sudo rm -rf \"\$PROJECT_DIR\"
            fi

            echo 'Cloning repository...'
            git clone --branch \"$BRANCH_NAME\" https://github.com/persistsolution/kwick-ui-frontend.git \"\$PROJECT_DIR\"
            cd \"\$PROJECT_DIR\"

            # Install Bun if not already installed
            if ! command -v bun &> /dev/null; then
              echo 'Installing Bun...'
              curl -fsSL https://bun.sh/install | bash
              export PATH=\"\$HOME/.bun/bin:\$PATH\"
              source ~/.bashrc
            fi

            echo 'Installing dependencies with Bun...'
            bun install --no-cache

            # Restart or start the application with PM2
            if pm2 list | grep -q \"$BRANCH_NAME\"; then
              echo 'Restarting existing Bun application with PM2...'
              pm2 restart \"$BRANCH_NAME\" --update-env
            else
              echo 'Starting new Bun application with PM2...'
              pm2 start \"bun dev --port \$PORT\" --name \"$BRANCH_NAME\" --cwd \"$PROJECT_DIR\"
            fi

            pm2 save
            echo 'Deployment for branch: $BRANCH_NAME completed.'
          "
