name: Deploy React App to Port 5177

on:
  push:
    branches:
      - main
      - dev
      - test
      - stag
      - dockertest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Branch Name
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Extracted Branch Name: $BRANCH_NAME"
          if [ -z "$BRANCH_NAME" ]; then
            echo "Error: Branch name is empty!"
            exit 1
          fi

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 on Port 5177
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            set -e
            echo 'Connected to EC2. Deploying branch to port 5177'
      
            PROJECT_DIR='/home/ubuntu/kwick-ui-frontend/5177'
            DOCKER_IMAGE='kwick-ui-frontend-5177'
            DOCKER_CONTAINER='kwick-ui-5177'
            PORT=5177
      
            echo \"Branch will run on port \$PORT\"
      
            echo \"Checking Docker installation...\"
            if ! command -v docker &> /dev/null; then
              echo 'Docker not found. Installing Docker...'
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              echo 'Docker installed successfully.'
            else
              echo 'Docker is already installed.'
            fi
      
            if [ -d \"\$PROJECT_DIR\" ]; then
              echo \"Cleaning up existing directory: \$PROJECT_DIR\"
              sudo rm -rf \"\$PROJECT_DIR\"
            fi
      
            echo \"Verifying branch existence...\"
            BRANCH_NAME='${BRANCH_NAME:-main}' # Use 'main' as fallback if empty
            git ls-remote --heads https://github.com/persistsolution/kwick-ui-frontend.git \"\$BRANCH_NAME\"
            if [ $? -ne 0 ]; then
                echo \"Error: Branch '\$BRANCH_NAME' does not exist in the repository!\"
                exit 1
            fi
      
            git clone --branch \"\$BRANCH_NAME\" https://github.com/persistsolution/kwick-ui-frontend.git \"\$PROJECT_DIR\"
            cd \"\$PROJECT_DIR\"
      
            echo 'Building Docker image...'
            docker build -t \$DOCKER_IMAGE .
      
            echo 'Stopping existing container...'
            docker stop \$DOCKER_CONTAINER || true
            docker rm \$DOCKER_CONTAINER || true
      
            echo 'Running Docker container...'
            docker run -d --name \$DOCKER_CONTAINER -p \$PORT:5177 \$DOCKER_IMAGE
      
            echo 'Deployment completed.'
          "
