name: Deploy React App with Docker

on:
  push:
    branches:
      - main
      - dev
      - test
      - stag
      - dockertest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log into Docker Hub using credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image from Dockerfile
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kwick-ui-frontend:$GITHUB_SHA .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/kwick-ui-frontend:$GITHUB_SHA

      # Optional: Deploy to EC2 and run Docker container
      - name: Deploy to EC2 and Run Docker container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            docker pull ${{ secrets.DOCKER_USERNAME }}/kwick-ui-frontend:$GITHUB_SHA
            docker run -d -p 5177:5177 --name kwick-ui-frontend-container ${{ secrets.DOCKER_USERNAME }}/kwick-ui-frontend:$GITHUB_SHA
          "
