name: Deploy React App

on:
  push:
    branches:
      - main
      - dev
      - test
      - stag

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          echo "Deploying branch: $BRANCH_NAME to EC2 instance at ${{ secrets.EC2_HOST }}"
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "bash -s" <<EOF
          set -e
          echo "Connected to EC2. Starting deployment for branch: $BRANCH_NAME"
          PROJECT_DIR="/home/ubuntu/kwick-ui-frontend"
          
          # Handle project directory existence
          if [ -d "$PROJECT_DIR" ]; then
            if [ -d "$PROJECT_DIR/.git" ]; then
              echo "Project directory exists and is a valid git repository. Pulling latest changes."
              cd $PROJECT_DIR
              git fetch origin $BRANCH_NAME
              git reset --hard origin/$BRANCH_NAME
            else
              echo "Directory exists but is not a valid git repository. Cleaning up."
              rm -rf $PROJECT_DIR
            fi
          fi
          
          # Clone repository if directory was cleaned or did not exist
          if [ ! -d "$PROJECT_DIR" ]; then
            echo "Cloning repository as the project directory does not exist."
            git clone https://github.com/persistsolution/kwick-ui-frontend.git $PROJECT_DIR
          fi
          
          # Ensure we are in the correct directory
          cd $PROJECT_DIR
          git checkout $BRANCH_NAME
          
          bun install --no-cache
          
          echo "Installing dependencies completed. Restarting the service for $BRANCH_NAME."
          case "$BRANCH_NAME" in
            main)
              pm2 restart main --update-env || pm2 start "bun dev --port 5173" --name main
              ;;
            dev)
              pm2 restart dev --update-env || pm2 start "bun dev --port 5174" --name dev
              ;;
            test)
              pm2 restart test --update-env || pm2 start "bun dev --port 5175" --name test
              ;;
            stag)
              pm2 restart stag --update-env || pm2 start "bun dev --port 5176" --name stag
              ;;
          esac
          echo "Deployment for $BRANCH_NAME completed."
          EOF
