name: Deploy React App

on:
  push:
    branches:
      - main
      - dev
      - test
      - stag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          # Extract branch name
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch Name: $BRANCH_NAME"

          # Validate branch name
          if [ -z "$BRANCH_NAME" ]; then
            echo "Error: Branch name is empty!"
            exit 1
          fi

          echo "Deploying branch: $BRANCH_NAME to EC2 instance at ${{ secrets.EC2_HOST }}"
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            set -e
            echo 'Connected to EC2. Starting deployment for branch: $BRANCH_NAME'

            # Define variables
            PROJECT_DIR='/home/ubuntu/kwick-ui-frontend/$BRANCH_NAME'
            PORT_MAP=('main:5173' 'dev:5174' 'test:5175' 'stag:5176')
            PORT=0

            # Get the port based on branch name
            for MAPPING in \${PORT_MAP[@]}; do
              if [[ \"\$MAPPING\" == \"\$BRANCH_NAME\"* ]]; then
                PORT=\${MAPPING#*:}
                break
              fi
            done

            if [[ \"\$PORT\" -eq 0 ]]; then
              echo 'No port mapping found for branch: $BRANCH_NAME'
              exit 1
            fi

            echo 'Branch $BRANCH_NAME will run on port $PORT'

            # Ensure Bun is installed
            if ! command -v bun &> /dev/null; then
              echo 'Bun is not installed. Installing Bun...'
              curl -fsSL https://bun.sh/install | bash
              export PATH=\"\$HOME/.bun/bin:\$PATH\"
              source ~/.bashrc
            fi
            echo 'Bun is installed at: $(command -v bun)'

            # Debug and clean up existing directory for the branch
            if [ -d \"\$PROJECT_DIR\" ]; then
              echo 'Directory exists for branch. Cleaning up.'
              sudo chmod -R 777 \"\$PROJECT_DIR\"
              sudo rm -rf \"\$PROJECT_DIR\"
            fi

            # Clone the repository
            echo 'Cloning repository for branch: $BRANCH_NAME'
            git clone https://github.com/persistsolution/kwick-ui-frontend.git \"\$PROJECT_DIR\"

            # Navigate to the cloned directory
            cd \"\$PROJECT_DIR\"
            echo 'Switched to project directory: $(pwd)'

            # Checkout the correct branch
            echo 'Checking out branch: $BRANCH_NAME'
            git checkout \"$BRANCH_NAME\"

            # Install dependencies using Bun
            bun install --no-cache

            # Start or restart the application using PM2
            echo 'Restarting application for branch: $BRANCH_NAME on port: $PORT'
            if pm2 list | grep -q \"$BRANCH_NAME\"; then
              pm2 restart \"$BRANCH_NAME\" --update-env
            else
              pm2 start \"bun dev --port $PORT\" --name \"$BRANCH_NAME\" --cwd \"$PROJECT_DIR\"
            fi

            # Save PM2 process list
            pm2 save

            echo 'Deployment for branch: $BRANCH_NAME completed.'
          "
